USE DBANANA
GO

CREATE TRIGGER itemCascadeDelete
ON ITEMS
INSTEAD OF DELETE
AS
BEGIN
	DELETE FROM MEALS WHERE id IN (SELECT id FROM MEALS_ITEMS WHERE item_id=(SELECT id FROM deleted))
	DELETE FROM ORDERS WHERE id IN (SELECT id FROM ORDERS_ITEMS WHERE item_id=(SELECT id FROM deleted))
	DELETE FROM SUPPLY_ORDERS WHERE id IN (SELECT id FROM SUPPLY_ORDERS_ITEMS WHERE item_id=(SELECT id FROM deleted))
	DELETE FROM ITEMS WHERE id IN (SELECT id FROM deleted)
END
GO


/*
CREATE TRIGGER meal_itemCascadeDelete
ON MEALS_ITEMS
FOR DELETE
AS
	DELETE FROM MEALS
	WHERE  id IN (SELECT meal_id FROM deleted)
GO
*/

CREATE TRIGGER mealCascadeDelete
ON MEALS
INSTEAD OF DELETE
AS
BEGIN
	DELETE FROM MEALS_ITEMS
	WHERE  meal_id IN (SELECT id FROM deleted)
	DELETE FROM MEALS WHERE id IN (SELECT id FROM deleted)
END

GO

CREATE TRIGGER orderCascadeDelete
ON ORDERS
INSTEAD OF DELETE
AS
BEGIN
    DELETE FROM ORDERS_ITEMS 
	WHERE order_id IN (SELECT id from deleted)
	DELETE FROM ORDERS WHERE id IN (SELECT id FROM deleted)
END
GO

CREATE TRIGGER supply_orderCascadeDelete
ON SUPPLY_ORDERS
INSTEAD OF DELETE
AS
BEGIN
    DELETE FROM SUPPLY_ORDERS_ITEMS 
	WHERE supply_order_id in (SELECT id FROM deleted)
	DELETE FROM SUPPLY_ORDERS WHERE id IN (SELECT id FROM deleted)
END
GO


